### ISSUE TITLE
Suggestion: separate FSM functionality in dedicated ZendFsm package

### ISSUE THREAD

**Issue by holtkamp** [zendframework/ZendSearch#12]
We extensively use the concept of an FSM to model the lifecycle/behavior/dynamics of our Entities, which works great. We are still on Zend Framework 1 and now in the process of investigating an upgrade to ZF2. Since the introduction of ZF2 [I read some stuff about usage of FSM in the dispatch cycle] (http://framework.zend.com/wiki/pages/viewpage.action?pageId=18219425), so I kind of hoped that by now the FSM class was isolated from the ZendSearch package for easier re-use.

It is not though... Therefore the following suggestion:
- Is it an idea to isolate the AbstractFSM from the ZendSearch package in a separate ZendFsm package?
 - This way it can be re-used easier throughout both the Zend Framework and other libraries. The class documentation also [explicitly suggests this re-use] (https://github.com/zendframework/ZendSearch/blob/master/library/ZendSearch/Lucene/AbstractFSM.php#L18)
 - Makes more sense in terms of logical organization, what has an FSM (specifically) to do with search? It should be the other way around, ZendSearch depends on ZendFsm...
- In case a separate package is not an option: is it an idea to make the properties protected? Our 'own' FSM class, which extends the one in ZendSearch, can not
access the actions, events, etc. since they are defined as being private properties.

**Comment by holtkamp** [comment]
one year ping on this, would it hurt to make the properties protected?

**Comment by weierophinney** [comment]
We've essentially abandoned this component. The functionality in this repo isn't even up-to-date with its predecessor in ZF1. We have no plans to update it at this time, as it requires a ton of specialized knowledge, and will require significant effort to update to the latest versions of Lucene.

**Comment by holtkamp** [comment]
ok, did FSM functionality land in an other component? Unfortunately the aforementioned link about FSM functionality in the dispatch cycle is down, believe it was your article @weierophinney ...

Might it be considered to making the properties protected of the [ZF1 component](https://github.com/zendframework/zf1/blob/master/library/Zend/Search/Lucene/FSM.php)?

Otherwise this issue can be closed.

**Comment by weierophinney** [comment]
> ok, did FSM functionality land in an other component?

No, we never ended up creating an FSM component.

> Might it be considered to making the properties protected of the ZF1 component?

No; that would be a BC break.
