### ISSUE TITLE
AbstractFile::readInt(): Uninitialized string offset: 0

### ISSUE THREAD

**Issue by TiMESPLiNTER** [zendframework/ZendSearch#14]
There is a problem with the method `AbstractFile::readInt()` when you read from an empty file 4 bytes with 

``` php
$str = $this->_fread(4);
```

and you get an empty string. But when you access the chars of the empty string with

``` php
ord($str[0])
```

you get an "Uninitialized string offset: 0" error.

This happens sometimes if a cronjob starts the indexing process. I get then the following error:

```
ZendSearch\Lucene\Exception\RuntimeException: (8) "Uninitialized string offset: 0"
thrown in file: /.../libs/zendsearch-master/ZendSearch/Lucene/Index.php (Line: 154)
```

**Comment by Xerkus** [comment]
Closing as component is not maintained
