### ISSUE TITLE
The RC5 tag depends on non-existing zend/zend-stdlib: 2.0.0rc5

### ISSUE THREAD

**Issue by dantleech** [zendframework/ZendSearch#16]
The rc5 tag depends on non existant `zend/zend-stdlib:2.0.0rc5` because it uses `self.version`:

https://github.com/zendframework/ZendSearch/blob/release-2.0.0rc5/composer.json

I am having to alias the zend-stdlib in my composer.json

````javascript
        "zendframework/zend-stdlib": "2.3.1 as 2.0.0rc5",
````

**Comment by Nyholm** [comment]
:+1:  for a new release.

**Comment by Maks3w** [comment]
RC6 released
