### ISSUE TITLE
PHP 7 compatibillity

### ISSUE THREAD

**Issue by pascalwacker** [zendframework/ZendSearch#24]
When trying to use `ZendSearch` on Ubuntu 16.04, with PHP 7.0, the following exception get's thrown:

```
          [ZendSearch\Lucene\Exception\RuntimeException]  
          Can't obtain shared reading index lock  
```

**Comment by weierophinney** [comment]
This component is no longer maintained; the last PHP version it was tested against is 5.3.

**Comment by crnkovic** [comment]
Are there any alternatives? Except Algolia and Elastic.

**Comment by Xerkus** [comment]
Closing as component is not maintained
