### ISSUE TITLE
Too many file handles kept open

### ISSUE THREAD

**Issue by mburtscher** [zendframework/ZendSearch#6]
ZendSearch opens file handles for all index files and usually keeps them open until the index is closed. On some systems this will lead to a **"Too many files open"** error. As a result even includes (like including the `RuntimeException.php` won't work). This happens especially on Sun Solaris machines where you have a more restrictive file handle limit.

File handles should be closed and not be kept open in parallel which will have negative impact on performance for sure. But a slow search engine is better than a search engine that does not work at all.

**Comment by Xerkus** [comment]
Closing as component is not maintained
